# --- DEPLOYMENT CONFIG ---
appName: myhelmapp
image:
  repository: devopsjourney1/mywebapp
  tag: latest

# --- GENERAL CONFIG ---
namespace: default

# --- CONFIGMAP CONFIG ---
configMap:
  name: helmappconfigmapv1.2
  data:
    customHeader: "Welcome to My COOL Web App"
